import 'package:flutter/material.dart';

Map<String, IconData> iconPackage = {
  'menu': Icons.menu,
  'maintoday': Icons.settings_system_daydream,
  'dashboard': Icons.dashboard,
  'role': Icons.group_work,
  'info': Icons.info,
  'person': Icons.person,
  'image': Icons.image,
  'video': Icons.video_call,
  'message': Icons.message,
  'dict': Icons.dialpad_outlined,
  'subsystem': Icons.home_work_outlined,
  'dept':Icons.deck,
  'coupon':Icons.attach_money,
  'money': Icons.money,
  'menu_child':Icons.arrow_right,
  //'menu_sub_child':Icons.,
  'assessment':Icons.assessment,
  'userGroup':Icons.group,
  'home':Icons.home,
  'shop':Icons.storefront,
  'order':Icons.delivery_dining,
  'api':Icons.api_outlined,
  'mapping':Icons.connect_without_contact_rounded,
  'notice':Icons.dashboard_rounded,
  'business':Icons.business,
  'customer':Icons.person_search_rounded,
  'mileage':Icons.receipt,
  'calculate':Icons.calculate,
  'request':Icons.post_add,
  'log':Icons.build_circle,
  'code':Icons.format_list_numbered,
  'manage':Icons.manage_accounts_outlined,
  'review':Icons.rate_review,
  'redeem':Icons.redeem,
};
